AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless-retail-api — Phase 7 (HTTP API + DDB + Cognito + API Access Logs)

Parameters:
  AlarmEmail:
    Type: String
    Description: Email address to receive CloudWatch alarm notifications

Globals:
  Function:
    Timeout: 6
    Runtime: python3.13
    Environment:
      Variables:
        CARDS_TABLE: !Ref CardsTable

Resources:

  # --------------------------------------------------------------------------
  # CloudWatch Logs group for API Gateway access logs
  # --------------------------------------------------------------------------
  HttpApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigw/${AWS::StackName}-http"
      RetentionInDays: 14

  # --------------------------------------------------------------------------
  # SNS topic + email subscription for alarm notifications
  # --------------------------------------------------------------------------
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-alerts"

  NotificationSubscriptionEmail:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref NotificationTopic
      Protocol: email
      Endpoint: !Ref AlarmEmail


  # --------------------------------------------------------------------------
  # CloudWatch Alarm — API Gateway 5XX errors (alerts via SNS)
  # --------------------------------------------------------------------------
  Api5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-ApiGateway-5XXError"
      AlarmDescription: Triggers when API Gateway returns >=1 5XX in 5 minutes on $default stage
      Namespace: AWS/ApiGateway
      MetricName: 5XXError
      Statistic: Sum
      Period: 300              # 5 minutes
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      Dimensions:
        - Name: ApiId
          Value: !Ref HttpApiGateway     # resolves to your API ID (e.g., mzqly42g8g)
        - Name: Stage
          Value: $default
      AlarmActions:
        - !Ref NotificationTopic         # send to the SNS topic you created


  # --------------------------------------------------------------------------
  # Cognito resources for JWT authorizer
  # --------------------------------------------------------------------------
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-user-pool"
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub "${AWS::StackName}-app-client"
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  # --------------------------------------------------------------------------
  # HTTP API Gateway (Cognito authorizer + access logs)
  # --------------------------------------------------------------------------
  HttpApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      AccessLogSettings:
        DestinationArn: !GetAtt HttpApiAccessLogs.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","routeKey":"$context.routeKey","path":"$context.path","status":"$context.status","protocol":"$context.protocol","responseLength":"$context.responseLength","integrationError":"$context.integrationErrorMessage","authorizerError":"$context.authorizer.error","jwtPrincipalId":"$context.authorizer.principalId"}'
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['GET','POST','PUT','DELETE','OPTIONS']
        AllowHeaders: ['*']
      Auth:
        Authorizers:
          CognitoAuthorizer:
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
              audience:
                - !Ref UserPoolClient
            IdentitySource: "$request.header.Authorization"

  # --------------------------------------------------------------------------
  # DynamoDB Table
  # --------------------------------------------------------------------------
  CardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CardsTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  # --------------------------------------------------------------------------
  # Lambda function router (main handler in HelloWorldFunction/app.py)
  # --------------------------------------------------------------------------
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: app.lambda_handler
      Architectures: [x86_64]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CardsTable
      Environment:
        Variables:
          CARDS_TABLE: !Ref CardsTable
          LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: cards-api
      Tracing: Active
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Path: /hello
            Method: GET
        GetCards:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Path: /cards
            Method: GET
        GetCardById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Path: /cards/{cardId}
            Method: GET
        GetTop3:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Path: /cards/top3
            Method: GET
        SeedCards:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Path: /cards/seed
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  ApiEndpoint:
    Description: HTTP API base URL ($default stage)
    Value: !Sub "https://${HttpApiGateway}.execute-api.${AWS::Region}.amazonaws.com"

  CognitoUserPoolId:
    Description: Created Cognito User Pool ID
    Value: !Ref UserPool

  CognitoAppClientId:
    Description: Created Cognito App Client ID
    Value: !Ref UserPoolClient
